language: cpp

env:
  - CMAKE_BUILD_TYPE=Debug

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

sudo: required

dist: trusty

matrix:
  exclude:
    # the default is too old - doesn't know make_unique()
    - compiler: clang
      os: linux

before_install:
  - if [ "$TRAVIS_OS_NAME" = linux ]; then sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y ; fi
  # in case the default sources yield hashsum errors ...
  # from https://github.com/The-Compiler/qutebrowser/blob/master/scripts/dev/ci_install.py#L71-L74
  - if [ "$TRAVIS_OS_NAME" = linux ]; then if sudo apt-get update -qq ; then true; else sudo sed -i 's/us-central1\.gce/us/' /etc/apt/sources.list ; sudo apt-get update -qq ; fi ; fi
  - if [ "$TRAVIS_OS_NAME" = linux -a "$CXX" = g++ ]; then apt-get install -qq gcc-4.9 g++-4.9 ; export CXX=g++-4.9; fi
  - if [ "$TRAVIS_OS_NAME" = linux ]; then sudo apt-get install -qq libboost-dev libboost-test-dev libboost-system-dev libboost-filesystem-dev ; fi
  - if [ "$TRAVIS_OS_NAME" = linux ]; then sudo apt-get install -qq ragel ; fi
  - if [ "$TRAVIS_OS_NAME" = osx   ]; then brew update ; fi
  - if [ "$TRAVIS_OS_NAME" = osx   ]; then brew install ragel ; fi

# install:

before_script:
  - uname -a
  - mkdir build
  - cd build
  # PWD -> build
  - cmake -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE ..

# PWD -> build
script: make -j1 grammar grammar_static ged check
